POST localhost:8080/attach/upload
Content-Type:multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA0MTkxMzYsImlkIjoxLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwNTA1NTM2LCJpc3MiOiJLdW5VelRlc3QifQ.oH31zPGUeJH7RwjDdERJJ-RDSmcH3NY4_piRT8X0FDiH6h3t8mAM5ruIpi24COj7fieaaqQtL39kRYhGcysb8A

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="testvideo.mp4"

< C:\Users\HP\Desktop\test\testvideo.mp4

### LOAD FILE
GET localhost:8080/attach/open/7509d905-777b-45ba-b9c0-450f8e730c37.mp4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAwNzg0NzksImlkIjoxLCJ1c2VybmFtZSI6Im11emFmZmFybWlrZTJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MjAxNjQ4NzksImlzcyI6Ikt1blV6VGVzdCJ9.2IO07Un63P1ds5HpfGWyVRKHxfETrUCvgCinkHhJhtglE_dhY3g5rTtwphTuQOdsqY_JcifQoZ4Mgm6cJLLKWw


### DOWNLOAD A FILE
GET localhost:8080/attach/download/7509d905-777b-45ba-b9c0-450f8e730c37.mp4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTk4MjMxNTUsImlkIjoxLCJ1c2VybmFtZSI6Im11emFmZmFybWlrZTJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MTk5MDk1NTUsImlzcyI6Ikt1blV6VGVzdCJ9.MBOi6b6hW3jvi6QbpX7qz4u4cjVLKgGHllL5yQVk_U_d0UyBoE77uk8538dPyTm5Ry7yL1Y0KGsow2NHwry02A

###PAGINATION
POST localhost:8080/attach/pagination
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTk4MjMxNTUsImlkIjoxLCJ1c2VybmFtZSI6Im11emFmZmFybWlrZTJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MTk5MDk1NTUsImlzcyI6Ikt1blV6VGVzdCJ9.MBOi6b6hW3jvi6QbpX7qz4u4cjVLKgGHllL5yQVk_U_d0UyBoE77uk8538dPyTm5Ry7yL1Y0KGsow2NHwry02A

### DELETE
DELETE localhost:8080/attach/delete/662b3e64-0e9c-442c-ae3e-dccb8c61b0ed.mp4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTk4MjMxNTUsImlkIjoxLCJ1c2VybmFtZSI6Im11emFmZmFybWlrZTJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MTk5MDk1NTUsImlzcyI6Ikt1blV6VGVzdCJ9.MBOi6b6hW3jvi6QbpX7qz4u4cjVLKgGHllL5yQVk_U_d0UyBoE77uk8538dPyTm5Ry7yL1Y0KGsow2NHwry02A