### Profile registration
POST http://localhost:8080/auth/registrationEmail
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "urinovshokirjon@gmail.com",
  "password": "12345"
}

### Profile login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "urinovshokirjon93@gmail.com",
  "password": "12345"
}

### Profile update email
PUT http://localhost:8080/profile/updateEmail?
    newEmail=urinovshokirjon93@gmail.com
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTk0NjE5MzIsImlkIjoxLCJ1c2VybmFtZSI6InVyaW5vdnNob2tpcmpvbkBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzE5NTQ4MzMyLCJpc3MiOiJLdW5VelRlc3QifQ.j683qHzAMo2JKYMh1FHhnMaFU_TU7xUcTv7yYhdt7afOXmb8A0hxhqdkq8q-S4mPr8_xYELwyCi0V9bhYxCJrg

### Profile update name, surname
PUT http://localhost:8080/profile/updateDetail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTk3MjM0NjksImlkIjoxLCJ1c2VybmFtZSI6InVyaW5vdnNob2tpcmpvbjkzQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MTk4MDk4NjksImlzcyI6Ikt1blV6VGVzdCJ9.7Imh4VhpSKiCe7uuCnY6LZkBhvQiJoiDcd-T86uX0oYY3c_xbteRnsux0-S6Kej8EJz7T01U85sZEtgTr8EgsQ

{
  "name": "Alijon",
  "surname": ""
}