### Create subscription
POST localhost:8080/subscription/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA1OTUyNTAsImlkIjoxLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwNjgxNjUwLCJpc3MiOiJLdW5VelRlc3QifQ.64JGa-a_TpvBA-M9ekbdDOieiZ9XWQzYQWnXEO8GeeZPzFGXqUqT1vFpvi4uxQJre3DgEb2xv6AuEbyv_i_iCg

{
  "channelId": "0cc55e68-2eba-46f0-826a-c77afa452819",
  "notificationType": "ALL"
}

### UPDATE STATUS
PUT localhost:8080/subscription/update-status/0cc55e68-2eba-46f0-826a-c77afa452819?status=ACTIVE
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA1OTUyNTAsImlkIjoxLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwNjgxNjUwLCJpc3MiOiJLdW5VelRlc3QifQ.64JGa-a_TpvBA-M9ekbdDOieiZ9XWQzYQWnXEO8GeeZPzFGXqUqT1vFpvi4uxQJre3DgEb2xv6AuEbyv_i_iCg

### UPDATE STATUS
PUT localhost:8080/subscription/update-notification-type/0cc55e68-2eba-46f0-826a-c77afa452819?notification-type=NONE
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA1OTUyNTAsImlkIjoxLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwNjgxNjUwLCJpc3MiOiJLdW5VelRlc3QifQ.64JGa-a_TpvBA-M9ekbdDOieiZ9XWQzYQWnXEO8GeeZPzFGXqUqT1vFpvi4uxQJre3DgEb2xv6AuEbyv_i_iCg

### GET ALL SUBSCRIPTION
GET localhost:8080/subscription/subscription-list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA1OTUyNTAsImlkIjoxLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwNjgxNjUwLCJpc3MiOiJLdW5VelRlc3QifQ.64JGa-a_TpvBA-M9ekbdDOieiZ9XWQzYQWnXEO8GeeZPzFGXqUqT1vFpvi4uxQJre3DgEb2xv6AuEbyv_i_iCg

### GET ALL SUBSCRIPTION
GET localhost:8080/subscription/subscription-list-admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA2MDYyOTQsImlkIjoyLCJ1c2VybmFtZSI6Im11emFmZmFybWlrZTJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MjA2OTI2OTQsImlzcyI6Ikt1blV6VGVzdCJ9.X3LzmytPQ4b_e4m9KqYJQIgb3AeF7PQ5nLxZRy2Td-_BG35lf9E6IGT9ol6Ql7PvY877It7U2p-Z295JNzTCzQ
