### CREATE VIDEO
POST localhost:8080/video/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAxNzM2OTEsImlkIjoyLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwMjYwMDkxLCJpc3MiOiJLdW5VelRlc3QifQ.4esDlZUlA35n35rmUQ97jzFOErd5TXSwKqyuMLAqZpsKjUMujERYw6iamWiEQNfYZvg0C1rN7gzoodrsatYrZg

{
  "title": "Dasturlash sirlari",
  "categoryId": 1,
  "attachId": "6f4d527d-8c09-41fc-82f0-6a15d3cffdbe.mp4",
   "type": "VIDEO",
  "channelId": "d00293c7-fe3f-4213-a580-24dcb5c736ec",
  "tags": [1,2]
}

### UPDATE VIDEO DETAIL
PUT localhost:8080/video/update-video-details
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAwNzk1MDIsImlkIjoyLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwMTY1OTAyLCJpc3MiOiJLdW5VelRlc3QifQ.6Pa6j3UmZ9huB4HIQWoiWbwxUdh56MAObRXnh2Q70grBORsDnxd5XE3as1ABmo-Q_ayhDB5yO5OQILDHah6f2g

{
  "title": "Mother tongue",
  "status": "PUBLIC",
  "attachId": "6f4d527d-8c09-41fc-82f0-6a15d3cffdbe.mp4"
}

### UPDATE VIDEO STATUS
PUT localhost:8080/video/update-status/6f4d527d-8c09-41fc-82f0-6a15d3cffdbe.mp4?status=PUBLIC
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAwNzk1MDIsImlkIjoyLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwMTY1OTAyLCJpc3MiOiJLdW5VelRlc3QifQ.6Pa6j3UmZ9huB4HIQWoiWbwxUdh56MAObRXnh2Q70grBORsDnxd5XE3as1ABmo-Q_ayhDB5yO5OQILDHah6f2g

### INCREMENT VIEW COUNT
PUT localhost:8080/video/increase-view-count?attachId=6f4d527d-8c09-41fc-82f0-6a15d3cffdbe.mp4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAwNzk1MDIsImlkIjoyLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwMTY1OTAyLCJpc3MiOiJLdW5VelRlc3QifQ.6Pa6j3UmZ9huB4HIQWoiWbwxUdh56MAObRXnh2Q70grBORsDnxd5XE3as1ABmo-Q_ayhDB5yO5OQILDHah6f2g

### PAGINATION
GET localhost:8080/video/pagination/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAwNzk1MDIsImlkIjoyLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwMTY1OTAyLCJpc3MiOiJLdW5VelRlc3QifQ.6Pa6j3UmZ9huB4HIQWoiWbwxUdh56MAObRXnh2Q70grBORsDnxd5XE3as1ABmo-Q_ayhDB5yO5OQILDHah6f2g

### SEARCH BY TITLE
GET localhost:8080/video/search-by-title?title=tongue
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAwNzk1MDIsImlkIjoyLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwMTY1OTAyLCJpc3MiOiJLdW5VelRlc3QifQ.6Pa6j3UmZ9huB4HIQWoiWbwxUdh56MAObRXnh2Q70grBORsDnxd5XE3as1ABmo-Q_ayhDB5yO5OQILDHah6f2g

### SEARCH BY TAG ID
GET localhost:8080/video/get-by-tag-id/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAxNzM2OTEsImlkIjoyLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwMjYwMDkxLCJpc3MiOiJLdW5VelRlc3QifQ.4esDlZUlA35n35rmUQ97jzFOErd5TXSwKqyuMLAqZpsKjUMujERYw6iamWiEQNfYZvg0C1rN7gzoodrsatYrZg

