### CREATE VIDEO
POST localhost:8080/video/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA0MTkxMzYsImlkIjoxLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwNTA1NTM2LCJpc3MiOiJLdW5VelRlc3QifQ.oH31zPGUeJH7RwjDdERJJ-RDSmcH3NY4_piRT8X0FDiH6h3t8mAM5ruIpi24COj7fieaaqQtL39kRYhGcysb8A

{
  "title": "Dasturlash sirlari 2",
  "categoryId": 1,
  "attachId": "58375103-f0c4-4fbc-b28a-70fc076c5829.mp4",
   "type": "VIDEO",
  "channelId": "0cc55e68-2eba-46f0-826a-c77afa452819",
  "tags": [1,2]
}

### UPDATE VIDEO DETAIL
PUT localhost:8080/video/update-video-details
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAwNzk1MDIsImlkIjoyLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwMTY1OTAyLCJpc3MiOiJLdW5VelRlc3QifQ.6Pa6j3UmZ9huB4HIQWoiWbwxUdh56MAObRXnh2Q70grBORsDnxd5XE3as1ABmo-Q_ayhDB5yO5OQILDHah6f2g

{
  "title": "Mother tongue",
  "status": "PUBLIC",
  "attachId": "6f4d527d-8c09-41fc-82f0-6a15d3cffdbe.mp4"
}

### UPDATE VIDEO STATUS
PUT localhost:8080/video/update-status/6f4d527d-8c09-41fc-82f0-6a15d3cffdbe.mp4?status=PUBLIC
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAwNzk1MDIsImlkIjoyLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwMTY1OTAyLCJpc3MiOiJLdW5VelRlc3QifQ.6Pa6j3UmZ9huB4HIQWoiWbwxUdh56MAObRXnh2Q70grBORsDnxd5XE3as1ABmo-Q_ayhDB5yO5OQILDHah6f2g

### INCREMENT VIEW COUNT
PUT localhost:8080/video/increase-view-count?attachId=6f4d527d-8c09-41fc-82f0-6a15d3cffdbe.mp4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAwNzk1MDIsImlkIjoyLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwMTY1OTAyLCJpc3MiOiJLdW5VelRlc3QifQ.6Pa6j3UmZ9huB4HIQWoiWbwxUdh56MAObRXnh2Q70grBORsDnxd5XE3as1ABmo-Q_ayhDB5yO5OQILDHah6f2g

### PAGINATION
GET localhost:8080/video/pagination/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAwNzk1MDIsImlkIjoyLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwMTY1OTAyLCJpc3MiOiJLdW5VelRlc3QifQ.6Pa6j3UmZ9huB4HIQWoiWbwxUdh56MAObRXnh2Q70grBORsDnxd5XE3as1ABmo-Q_ayhDB5yO5OQILDHah6f2g

### SEARCH BY TITLE
GET localhost:8080/video/search-by-title?title=tongue
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAwNzk1MDIsImlkIjoyLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwMTY1OTAyLCJpc3MiOiJLdW5VelRlc3QifQ.6Pa6j3UmZ9huB4HIQWoiWbwxUdh56MAObRXnh2Q70grBORsDnxd5XE3as1ABmo-Q_ayhDB5yO5OQILDHah6f2g

### SEARCH BY TAG ID
GET localhost:8080/video/get-by-tag-id/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAxNzM2OTEsImlkIjoyLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwMjYwMDkxLCJpc3MiOiJLdW5VelRlc3QifQ.4esDlZUlA35n35rmUQ97jzFOErd5TXSwKqyuMLAqZpsKjUMujERYw6iamWiEQNfYZvg0C1rN7gzoodrsatYrZg

### GET VIDEO FULL INFO
GET localhost:8080/video/get-video-by-id/60e2a11c-8cb1-4e47-98ce-428a6baceea4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAzNDk2MjAsImlkIjoxLCJ1c2VybmFtZSI6Im11emFmZmFybWlrZTJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MjA0MzYwMjAsImlzcyI6Ikt1blV6VGVzdCJ9.alS40KATn16PM5JGXuHagv_49eR9WdyAso6-_SHhOChTNmVcYmE6Dy5RAvuz_1tC_9C6o6By55bfHXMINYr80A


### GET ALL VIDEOS PAGINATION
GET localhost:8080/video/get-video-list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAzNDk2MjAsImlkIjoxLCJ1c2VybmFtZSI6Im11emFmZmFybWlrZTJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MjA0MzYwMjAsImlzcyI6Ikt1blV6VGVzdCJ9.alS40KATn16PM5JGXuHagv_49eR9WdyAso6-_SHhOChTNmVcYmE6Dy5RAvuz_1tC_9C6o6By55bfHXMINYr80A

### GET ALL VIDEOS OF A CHANNEL
GET localhost:8080/video/channel/0cc55e68-2eba-46f0-826a-c77afa452819/videos

