###LIKE OR DISLIKE
POST localhost:8080/video-like/like&dislike/60e2a11c-8cb1-4e47-98ce-428a6baceea4?likeStatus=DISLIKE
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA2ODE5MjMsImlkIjoxLCJ1c2VybmFtZSI6Im9ydGlxb3ZtdXphZmZhcjE3MUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzIwNzY4MzIzLCJpc3MiOiJLdW5VelRlc3QifQ.hYLmQtivGPUlPWRW4RhHS2Lo6Z4BmE4agVtJPNIHnYA2WnNgig9uvr-54jgnfuTW9h_wLPtRnJEkDEaomyTqng

### GET USER LIKED VIDEOS
GET localhost:8080/video-like/user-liked-videos/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA3NzY1MzUsImlkIjoyLCJ1c2VybmFtZSI6Im11emFmZmFybWlrZTJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MjA4NjI5MzUsImlzcyI6Ikt1blV6VGVzdCJ9.VW5t0Bnf25IE-wx4rFolQhXWMy_cWpt1_hYWt1g2kb0icXdB7MvzpM1E74-g5BprsmKTW84UaCfqpOb3n3ZsCA